services:
  bridge:
    image: ghcr.io/ethanjli/pallet-example-planktoscope-wio-bridge:sha-ae901d9
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PYTHONUNBUFFERED=1
