services:
  bridge:
    image: ghcr.io/ethanjli/pallet-example-planktoscope-wio-bridge:sha-c5068d8
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    extra_hosts:
      - host.docker.internal:host-gateway
