services:
  bridge:
    image: ghcr.io/ethanjli/pallet-example-planktoscope-wio-bridge:sha-a21f939
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

networks:
  default:
    name: none
    external: true
